name: ebidan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  # internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^2.7.2
  intl: ^0.20.2

  # need Firebase Remote Config for Force Update
  # plase use FirebaseCLI
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1

  uuid: ^4.5.1
  package_info_plus: ^8.3.0
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.69.0
  # mask_text_input_formatter: ^2.9.0
  # flutter_native_splash: ^2.4.0
  # url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # flutter_web_optimizer: ^1.4.2

flutter:
  uses-material-design: true
