name: ebidan
description: "A new Flutter project."
publish_to: 'none'
version: 0.5.0+15

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  # internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^2.7.2
  intl: ^0.20.2

  # need Firebase Remote Config for Force Update
  # plase use FirebaseCLI
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  in_app_purchase: ^3.2.3
  cloud_functions: ^6.0.4
  firebase_remote_config: ^6.1.1
  firebase_messaging: ^16.1.0
  shared_preferences: ^2.5.3

  uuid: ^4.5.1
  package_info_plus: ^8.3.0
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.69.0
  url_launcher: ^6.3.2
  month_year_picker: ^0.5.0+1
  # mask_text_input_formatter: ^2.9.0
  # url_strategy: ^0.2.0
  collection: ^1.18.0
  avatar_glow: ^3.0.1
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_markdown_plus: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # flutter_web_optimizer: ^1.4.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#00BCD4"
  icon_background_color: "#00BCD4"
  image: assets/icons/logo_light.png
  image_dark: assets/icons/logo_dark.png
  android: true
  ios: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true      # biar status bar terlihat (opsional)
  android_12:
    color: "#00BCD4"
    icon_background_color: "#00BCD4"
    image: assets/icons/logo_light.png 
    image_dark: assets/icons/logo_dark.png